### ISSUE TITLE
Can't get rid of debug output

### ISSUE THREAD

**Issue by terencode** [juliagoda/antimicroX#92]
I tried starting it with `antimicroX --log-level="info"`  and also set the log message to "error/none" within the gui settings but it still shows a bunch of debug messages.

> antimicrox 2.25
ArchLinux

**Comment by juliagoda** [comment]
It should be better now, but it must be compiled from source from latest commit.

**Comment by terencode** [comment]
I did compile it from source with your latest commit but it's still not working.

**Comment by juliagoda** [comment]
You are right. I've changed it again. This time not only output to chosen file is adequate to settings but also the messages in console

**Comment by terencode** [comment]
Nice, the log level setting within the GUI works now.
However it crashes when trying to do it via CLI:
`antimicroX --log-level="debug"`
```
Thread 1 "antimicroX" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e136fb in Logger::getCurrentLogLevel() () from /usr/lib/libantilib.so
(gdb) bt
#0  0x00007ffff7e136fb in Logger::getCurrentLogLevel() () at /usr/lib/libantilib.so
#1  0x00007ffff7e446b6 in MessageHandler::myMessageOutput(QtMsgType, QMessageLogContext const&, QString const&) () at /usr/lib/libantilib.so
#2  0x00007ffff68c4ad8 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff68c4bea in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff68911d4 in QMessageLogger::warning(char const*, ...) const () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff6913a6b in  () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6913de9 in QCommandLineParser::isSet(QString const&) const () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff7d61487 in CommandLineUtility::parseArguments(QCommandLineParser*) () at /usr/lib/libantilib.so
#8  0x000055555555cbb6 in  ()
#9  0x00007ffff631f023 in __libc_start_main () at /usr/lib/libc.so.6
#10 0x000055555556067e in  ()
```

**Comment by terencode** [comment]
9b8fccf gets rid of it, thanks!
